{% set version = "2.6.3" %}

package:
  name: flex
  version: {{ version }}

source:
  fn: flex-{{ version }}.tar.gz
  url: https://github.com/westes/flex/releases/download/v{{ version }}/flex-{{ version }}.tar.gz
  sha256: 68b2742233e747c462f781462a2a1e299dc6207401dac8f0bbb316f48565c2aa

build:
  skip: true  # [win]
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - automake
    - libiconv  # [not linux and not win]
    - m4

  run:
    - libiconv  # [not linux and not win]
    - m4

test:
  commands:
    # CLI tests
    - flex --help

    # Include test
    - test -f ${PREFIX}/include/FlexLexer.h

    # Lib tests
    - test -f ${PREFIX}/lib/libfl.a
    - test -f ${PREFIX}/lib/libfl.dylib      # [osx]
    - test -f ${PREFIX}/lib/libfl.so         # [linux]

about:
  home: http://flex.sourceforge.net/
  license: BSD 2-Clause
  summary: The Fast Lexical Analyzer

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
