{% set version = "2.6.2" %}

package:
  name: flex
  version: {{ version }}

source:
  fn: flex-{{ version }}.tar.gz
  url: https://github.com/westes/flex/releases/download/v{{ version }}/flex-{{ version }}.tar.gz
  sha256: 9a01437a1155c799b7dc2508620564ef806ba66250c36bf5f9034b1c207cb2c9

build:
  skip: true  # [win]
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - automake
    - libiconv

  run:
    - libiconv

test:
  commands:
    # CLI tests
    - flex --help

    # Include test
    - test -f ${PREFIX}/include/FlexLexer.h

    # Lib tests
    - test -f ${PREFIX}/lib/libfl.a
    - test -f ${PREFIX}/lib/libfl_pic.a
    - test -f ${PREFIX}/lib/libfl.dylib      # [osx]
    - test -f ${PREFIX}/lib/libfl_pic.dylib  # [osx]
    - test -f ${PREFIX}/lib/libfl.so         # [linux]
    - test -f ${PREFIX}/lib/libfl_pic.so     # [linux]

about:
  home: http://flex.sourceforge.net/
  license: BSD 2-Clause
  summary: The Fast Lexical Analyzer

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
